### ISSUE TITLE
2023-11-15-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/mangement-team-todo#10]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)

# 분류된 작업
#### jujeon 
- 개인정보동의약관
- 모집글쓰기 작성 및 수정
- 히치하이킹
- 관리자페이지
- 커스텀에디터

#### hoslim
- 팀설정페이지
- 검색
- PWA

#### hyna
- 마이페이지, 프로필, 홈페이지설정
- 피어로그

#### hujeong
- 회원가입
- 탈퇴
- 마이페이지 개인정보

#### hyeokim2
- 메인페이지, 네비게이션바, 탭바
- 모집글 뷰
- DnD

#### jeyoon
- 팀페이지 메인화면
- 쪽지
- 툭박스(위젯)

#### woorikim
- 로그인
- 비밀번호 찾기
- 쇼케이스

#### haryu
- 알림 (nest)
- 쪽지
- socket (온라인 여부 관리 등)
- Algorithm (개인성향 측정, 팀평가)
#### jwee
- 게시판
- Algorithm (개인성향 측정, 팀평가)
- 피어로그
#### hyeongki
- 사용자추적
- 고나리자
- 인공지능 입출력 (chatGPT)
#### juhyelee
- 프로필
- 회원
- 피어로그
- 업적
#### junssong
- 회원
- 팀 (팀페이지, 팀설정 등)
#### wochae
- 알람 (스프링)
- 인공지능 입출력 (chatGPT)

**Comment by Paul2021-R** [comment]
- [ ] 깃액션 쪼개기
- [ ] DnD 관련 전체 밋업 준비하기 
- [ ] 소켓 모듈 문서화 진행하기 & 모듈 설계 전 담당자와 논의하기
- [ ] 쪽지 모듈 개선 전 문서화 진행하기 
- [ ] 쪽지 모듈 개선 
- [ ] 다른 모듈들에 대한 논의 일정 잡기

**Comment by sinryuji** [comment]
- [ ] team finish 추적
- [ ] 유저 활동 추적

**Comment by SaltySalt77** [comment]
#### 운영진
- [ ] 베스트 피어로그 & 스터디 디엠 발송
- [ ] 그린님 협의

#### 개발진
- [ ] 크로퍼
    - [ ] 이미지 업로드 버튼에 크로퍼 모달 추가 관련 논의
    - [ ] 크로퍼 추가하기
- [ ] DnD 관련 논의

**Comment by juhyeonlee134** [comment]
- [ ] DnD관련 논의
- [ ] 업적 정리

**Comment by yoouyeon** [comment]
- [ ] 캘린더 컴포넌트 구현 마무리 (https://github.com/peer-42seoul/Peer-Frontend/issues/308)
- [ ] 쪽지 모듈 개선 문서화 완료되면 작업하기 (https://github.com/peer-42seoul/Peer-Frontend/issues/302)
- [ ] 개선방안 고민 (https://github.com/peer-42seoul/Peer-Frontend/issues/270)

**Comment by HiHoi** [comment]
- [ ] 팀 설정 페이지 - 프로젝트에서 팀원 추가 기능
- [ ] 세부기획 - dnd dto 확정
- [ ] PWA 푸시알림 기능 설정

**Comment by wochae** [comment]
- [ ] 알람 디비 설계
- [ ] 과제물 제출 (1/2)
- [ ] QA

**Comment by KRimwoo** [comment]
- [ ] 소셜로그인 토큰처리
- [ ] 2스텝 기획읽기
- [ ] 1스텝 부분 디자인 적용을 위한 컴포넌트보완

**Comment by hyeon81** [comment]
- [ ] 어제 작업한 부분 pr 올리기
- [ ] 메인페이지, 모집글 페이지 qa
- [ ] 2차스텝 (dnd) 논의

**Comment by joonseong11** [comment]
## 앞으로 예정된 일
- [ ] 모집글쓰기 세부 디자인 입히기 논의
#### step2 히치하이킹
- [ ] 히치하이킹 기능구현을 위한 스와이프, 플립 기능 만들어보기
- [x] 히치하이킹 api 논의 (모집글 뷰 api과 비슷하지 않을까)
- [ ] 히치하이킹 레이아웃 구현
- [ ] 히치하이킹 스와이프 기능 구현
- [ ] 히치하이킹 플립 기능 구현
- [ ] 히치하이킹 해당 모집글로 리디렉션
#### step2 관리자페이지
- [x] 관리자페이지 와이어프레임 요청
- [ ] 관리자페이지 api 논의 (추가세부기획 필요)
- [ ] 관리자페이지 레이아웃 구현
- [ ] 관리자페이지 기능 구현 (와이어프레임 및 세부기획 필요)
#### step 2 커스텀 에디터
- [ ] ckeditor 기능 고려
- [ ] 에디터 기능 삽입
#### step1 QA
- [x] 인터뷰 답변 문제 발견 로직 변경 (api 와 데이터 타입 통일 및 로직 변경)
- [ ] 대표이미지 관련 부분에서 연동 의심 문제가 발견되서 해결예정
- [ ] 인터뷰 답이 달리면, 인터뷰 수정 못하게 반영
- [ ] 4주 반영

## 오늘 할 일
- [ ] 모집글쓰기 세부 디자인 입히기 논의
- [ ] 대표이미지 관련 부분에서 연동 의심 문제가 발견되서 해결예정

**Comment by perman0519** [comment]
- [ ] dnd 설계
- [ ] 버그 픽스
- [ ] enum valid 어노테이션 수정
- [ ] settting api 프로젝트 스터디 별로 로직 변경

**Comment by weejihye** [comment]
- [ ] 모집글 지원하기 - 중복지원 가능하게 변경  https://github.com/peer-42seoul/Peer-Backend/issues/307
- [ ] dto validation 추가- https://github.com/peer-42seoul/Peer-Backend/issues/230
- [ ] 인터뷰 답이 달리면 수정 못하게 반영 하는 부분은 제가 해야 할 일은 없나요?
- [ ] nhn storage로 file module 변경
