### ISSUE TITLE
2023-11-16-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/mangement-team-todo#11]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)

**Comment by HiHoi** [comment]
이슈 제목의 날짜가 이상하지만 일단 적겠습니다.

- [ ] PWA 알림 관련 DTO
- [ ] 디자인 미팅
- [ ] PWA 푸시 알림 작업
- [ ] 팀 설정 페이지 마무리
- [ ] 기타 프론트엔드 작업 막히는 부분 관리

**Comment by SaltySalt77** [comment]
#### 개발진
- [ ] 프로필
    - [ ] 크로퍼 적용한 코드 테스트 및 pr 올리기
- [ ] DnD 논의
- [ ] 디자인 미팅

**Comment by weejihye** [comment]
- [ ] 병원
- [ ] 차 수리
- [ ] 모집글 생성 오류 수정
- [ ] dto validation
- [ ] 팀게시판 crud
- [ ] nun 스토리지

**Comment by juhyeonlee134** [comment]
- [ ] philosopher
- [ ] ostep 가상 메모리
- [ ] pdf추출 알아보기

**Comment by Paul2021-R** [comment]
- [ ] PWA 알림 관련 DTO
- [ ] 디자인 미팅
- [ ] PWA 푸시 알림 작업
- [ ] 쪽지 개선하기 마무리
- [ ] 소켓 모듈 보안 기능 추가
- [ ] NGINX HTTPS 동작하도록 설정해보기

**Comment by joonseong11** [comment]
## 앞으로 예정된 일
- [ ] 모집글쓰기 세부 디자인 입히기 논의
#### step2 히치하이킹
- [ ] 히치하이킹 기능구현을 위한 스와이프, 플립 기능 만들어보기
- [x] 히치하이킹 api 논의 (모집글 뷰 api과 비슷하지 않을까)
- [ ] 히치하이킹 레이아웃 구현
- [ ] 히치하이킹 스와이프 기능 구현
- [ ] 히치하이킹 플립 기능 구현
- [ ] 히치하이킹 해당 모집글로 리디렉션
#### step2 관리자페이지
- [x] 관리자페이지 와이어프레임 요청
- [ ] 관리자페이지 api 논의 (추가세부기획 필요)
- [ ] 관리자페이지 레이아웃 구현
- [ ] 관리자페이지 기능 구현 (와이어프레임 및 세부기획 필요)
#### step 2 커스텀 에디터
- [ ] ckeditor 기능 고려
- [ ] 에디터 기능 삽입
#### step1 QA
- [x] 인터뷰 답변 문제 발견 로직 변경 (api 와 데이터 타입 통일 및 로직 변경)
- [x] 대표이미지 관련 부분에서 연동 의심 문제가 발견되서 해결예정
- [ ] 인터뷰 답이 달리면, 인터뷰 수정 못하게 반영
- [ ] 4주 반영

## 오늘 할 일
- [ ] pr 확인
- [ ] 모집글쓰기 세부 디자인 입히기 논의

**Comment by wochae** [comment]
- [ ] 스프링 알림 기능 파악하기
- [ ] 디비 설계
- [ ] 과제 2/2

**Comment by hyeon81** [comment]
- [ ] 1시 dnd 회의

여러가지 이슈 수정 (다 할 건 아니고... 빨리 되는것부터 처리할 예정)
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/318
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/316
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/295
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/275
- [ ] 세부옵션의 목표기간 슬라이더로 만들기
- [ ] 리모트에서 pc, 모바일 같이 나오는 현상 해결

- [ ] ssr시 토큰 담아서 가져오는 방법 연구
- [ ] 외주 작업 처리

**Comment by KRimwoo** [comment]
- [ ] 평가포인트 모으기
- [ ] so_long 평가받기

**Comment by sinryuji** [comment]
- [ ] oauth 쿠키 문제 해결하기

**Comment by perman0519** [comment]
- [ ] setting api  합치는 것 마무리
- [ ] qa 및 레퍼토링
- [ ] java 수업 듣기

**Comment by yoouyeon** [comment]
- [ ] PR 리뷰
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/308 반드시 마무리
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/302
- [ ] 모던 자바스크립트 deep dive 읽기
