### ISSUE TITLE
2023-11-17-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/mangement-team-todo#12]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)

**Comment by joonseong11** [comment]
## 앞으로 예정된 일
- [ ] 모집글쓰기 세부 디자인 입히기 논의
#### step2 히치하이킹
- [ ] 히치하이킹 기능구현을 위한 스와이프 기능 만들어보기 
- [x] 히치하이킹 기능구현을 위한 플립 기능 만들어보기
- [x] 히치하이킹 api 논의 (모집글 뷰 api과 비슷하지 않을까)
- [ ] 히치하이킹 레이아웃 구현
- [ ] 히치하이킹 스와이프 기능 구현
- [ ] 히치하이킹 플립 기능 구현
- [ ] 히치하이킹 해당 모집글로 리디렉션
#### step2 관리자페이지
- [x] 관리자페이지 와이어프레임 요청
- [ ] 관리자페이지 api 논의 (추가세부기획 필요)
- [ ] 관리자페이지 레이아웃 구현
- [ ] 관리자페이지 기능 구현 (와이어프레임 및 세부기획 필요)
#### step 2 커스텀 에디터
- [ ] ckeditor 기능 고려
- [ ] 에디터 기능 삽입
#### step1 QA
- [x] 인터뷰 답변 문제 발견 로직 변경 (api 와 데이터 타입 통일 및 로직 변경)
- [x] 대표이미지 관련 부분에서 연동 의심 문제가 발견되서 해결예정
- [ ] 인터뷰 답이 달리면, 인터뷰 수정 못하게 반영
- [ ] 4주 반영
- [ ] validation

## 오늘 할 일
- [ ] pr 확인
- [x] 디자인 미팅
- [ ] 인터뷰 답이 달리면, 인터뷰 수정 못하게 반영
- [ ] 4주 반영
- [ ] validation
- [ ] 히치하이킹 기능구현을 위한 스와이프 기능 만들어보기 
- [x] 히치하이킹 기능구현을 위한 플립 기능 만들어보기

**Comment by juhyeonlee134** [comment]
- [ ] DnD리뷰 및 파악
- [ ] 피어 로그 설계 및 논의
- [ ] pdf 추출

**Comment by sinryuji** [comment]
- [ ] 유저 가입 추적 리팩토링
- [ ] 유저 활동 추적 개발
- [ ] 신고기능 API 협의
- [ ] 신고기능 개발

**Comment by hyeon81** [comment]
- [ ] pr리뷰
- [ ] dnd 작업

**Comment by yoouyeon** [comment]
- [ ] 쪽지 api 테스트 후 PR 올리기
- [ ] 2step 담당범위 확인 후 위젯 구현 시작 (아마 이미지 위젯부터?) (확인 후 할 일 확실히 정하겠습니다 🥲)

**Comment by KRimwoo** [comment]
- [ ] so_long 평가받기
- [ ] 소셜회원가입 문제 원인 알아보고 해결 https://github.com/peer-42seoul/Peer-Frontend/issues/320
- [ ] 마이페이지 소셜회원 연동 버튼 추가하기 / 연동여부 표시하기

**Comment by SaltySalt77** [comment]
#### 운영진
- [ ] 인원수 파악 및 메뉴 선정
- [ ] 그린님 협의

#### 개발진
- [ ] 밀린 리뷰
- [ ] 크로퍼 적용한 프사 변경 pr
- [ ] DnD 데모
    - [ ] DnD 익히기

**Comment by Paul2021-R** [comment]
- [ ] 코드리뷰 진행
- [ ] dnd모듈 설명 
- [ ] 기획 나머지 작업
- [ ] 조디자이너 미팅

**Comment by HiHoi** [comment]
- [ ] DnD 데모 작업
- [ ] PWA api
- [ ] PWA 알림 작업
- [ ] 팀 설정 페이지 마무리

**Comment by perman0519** [comment]
- [ ] dnd 데모 작업
- [ ] java 수업 듣기
- [ ] 이미지 작업 분량 체크

**Comment by wochae** [comment]
- [ ] 오병이어
- [ ] Java 정리
- [ ] 스프링 소켓 구현 테스트 코드 만들기

**Comment by joonseong11** [comment]
- [ ] pr 확인
- [ ] 모집글쓰기 수정페이지 레이아웃 디자인 반영 마무리
- [ ] 백엔드 연동 다시 한번 체크
- [ ] 수정페이지, 인터뷰 답변 달려있는지 여부 api 추가 논의
- [ ] 논의후 인터뷰 답변 달려있으면 새로등록 막기
