### ISSUE TITLE
2023-11-20-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/mangement-team-todo#13]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)

**Comment by HiHoi** [comment]
- [ ] 디자인 미팅
- [ ] 리더 회의
- [ ] 백엔드 api url 포트 문제 논의
- [ ] PWA 알림 테스팅
- [ ] PWA 프리캐싱 기능
- [ ] 위젯 분량 분배

**Comment by Paul2021-R** [comment]
- [ ] JWT 토큰 validation 핫픽스 
- [ ] 세부 기획 추가 
- [ ] 리더스 회의 전 해야할 일 정리 
- [ ] 디자이너스 회의 전 해야할 일 정리
- [ ] ​향후 어떻게 진행할지에 대한 고민 정리

**Comment by KRimwoo** [comment]
- [ ] so_long 리트라이
- [ ] minitalk 시작하기
- [ ] 이전 pr conflict 수정
- [ ] 디자인 입히기 전 비밀번호 찾기, 회원가입페이지 와이어프레임 점검

**Comment by hyeon81** [comment]
- 여러가지 이슈 수정
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/318
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/316
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/295
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/275
- [ ] 세부옵션의 목표기간 슬라이더로 만들기
- [ ] 리모트에서 pc, 모바일 같이 나오는 현상 해결
- [ ] ssr시 토큰 담아서 가져오기

- [ ] 외주 작업 처리

**Comment by joonseong11** [comment]
## 앞으로 예정된 일
- [ ] 모집글쓰기 세부 디자인 입히기 논의
#### step2 히치하이킹
- [ ] 히치하이킹 기능구현을 위한 스와이프 기능 만들어보기 
- [x] 히치하이킹 기능구현을 위한 플립 기능 만들어보기
- [x] 히치하이킹 api 논의 (모집글 뷰 api과 비슷하지 않을까)
- [ ] 히치하이킹 레이아웃 구현
- [ ] 히치하이킹 스와이프 기능 구현
- [ ] 히치하이킹 플립 기능 구현
- [ ] 히치하이킹 해당 모집글로 리디렉션
#### step2 관리자페이지
- [x] 관리자페이지 와이어프레임 요청
- [ ] 관리자페이지 api 논의 (추가세부기획 필요)
- [ ] 관리자페이지 레이아웃 구현
- [ ] 관리자페이지 기능 구현 (와이어프레임 및 세부기획 필요)
#### step 2 커스텀 에디터
- [ ] ckeditor 기능 고려
- [ ] 에디터 기능 삽입
#### step1 QA
- [x] 인터뷰 답변 문제 발견 로직 변경 (api 와 데이터 타입 통일 및 로직 변경)
- [x] 대표이미지 관련 부분에서 연동 의심 문제가 발견되서 해결예정
- [ ] 인터뷰 답이 달리면, 인터뷰 수정 못하게 반영
- [x] 4주 반영
- [x] validation
- [x] https://github.com/peer-42seoul/Peer-Frontend/issues/293
- [x] https://github.com/peer-42seoul/Peer-Frontend/issues/327

## 오늘 할 일
- [ ] (외주) 서류 작업
- [ ] pr 확인
- [ ] 리더스 회의
- [ ] 디자이너미팅
- [ ] 인터뷰 답이 달리면, 인터뷰 수정 못하게 반영
- [ ] 히치하이킹 기능구현을 위한 스와이프 기능 만들어보기 
- [ ] 히치하이킹 카드 레이아웃 구현
- [ ] 히치하이킹 플립 기능 구현

**Comment by wochae** [comment]
- [ ] nginx 쿠킹
- [ ] 스프링 websocket 공부
- [ ] 자바 11 학습

**Comment by juhyeonlee134** [comment]
- [ ] ostep : 페이징 마무리
- [ ] philosophers
- [ ] mongoDB

**Comment by sinryuji** [comment]
- [ ] 유저 활동 추적 개발

**Comment by yoouyeon** [comment]
- [ ] 팀 공지사항 페이지 api 제외한 부분 완성하기
- [ ] (팀 공지사항 기능 파악 완료되면) api 논의하기
- [ ] PR 확인
