### ISSUE TITLE
2023-11-21-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/mangement-team-todo#14]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)

**Comment by Paul2021-R** [comment]
- [ ] JWT validation 핫픽스 
- [ ] 전체 회의 주제 및 대응 
- [ ] 세부 기획 점검 
- [ ] 백엔드 상황 대응

**Comment by SaltySalt77** [comment]
#### 운영진
- [ ] 메뉴 정리
- [ ] 리애 합의
- [ ] 그린님 전달
- [ ] 운영진 회의

#### 개발진
- [ ] mui 팔레트 커스텀

**Comment by hyeon81** [comment]
- [ ] pr 확인
- [ ] 어제 작업한 내용 pr 올리기
- [ ] dnd crud 연동 확인
- [ ] ssr 토큰 저장 방식 논의 (쿠키로 할지... 세션으로 할지...)
- [ ] 기타 이슈 픽스

**Comment by weejihye** [comment]
- [ ] exam05

**Comment by juhyeonlee134** [comment]
### Peer
- [ ] 오브젝트 스토리지 적용되었으면 거기에 맞춰 수정
---
### 42
- [ ] philosophers

**Comment by joonseong11** [comment]
## 앞으로 예정된 일
- [ ] 모집글쓰기 세부 디자인 입히기 논의
#### step2 히치하이킹
- [ ] 히치하이킹 기능구현을 위한 스와이프 기능 만들어보기 
- [x] 히치하이킹 기능구현을 위한 플립 기능 만들어보기
- [x] 히치하이킹 api 논의 (모집글 뷰 api과 비슷하지 않을까)
- [ ] 히치하이킹 레이아웃 구현
- [ ] 히치하이킹 스와이프 기능 구현
- [ ] 히치하이킹 플립 기능 구현
- [ ] 히치하이킹 해당 모집글로 리디렉션
#### step2 관리자페이지
- [x] 관리자페이지 와이어프레임 요청
- [ ] 관리자페이지 api 논의 (추가세부기획 필요)
- [ ] 관리자페이지 레이아웃 구현
- [ ] 관리자페이지 기능 구현 (와이어프레임 및 세부기획 필요)
#### step 2 커스텀 에디터
- [ ] ckeditor 기능 고려
- [ ] 에디터 기능 삽입
#### step1 QA
- [x] 인터뷰 답변 문제 발견 로직 변경 (api 와 데이터 타입 통일 및 로직 변경)
- [x] 대표이미지 관련 부분에서 연동 의심 문제가 발견되서 해결예정
- [ ] 인터뷰 답이 달리면, 인터뷰 수정 못하게 반영
- [x] 4주 반영
- [x] validation
- [x] https://github.com/peer-42seoul/Peer-Frontend/issues/293
- [x] https://github.com/peer-42seoul/Peer-Frontend/issues/327

## 오늘 할 일
- [ ] pr 확인
- [ ] 모집글쓰기 디자인 반영
- [ ] 인터뷰 답이 달리면, 인터뷰 수정 못하게 반영
- [ ] 히치하이킹 기능구현을 위한 스와이프 기능 만들어보기 
- [ ] 히치하이킹 카드 레이아웃 구현
- [ ] 히치하이킹 플립 기능 구현

**Comment by yoouyeon** [comment]
- [ ] PR 확인
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/338#issue-2002843422 마무리
- [ ] 공지사항 게시판 기능 정의 다시 확인 -> api논의

**Comment by sinryuji** [comment]
- [ ] 유저 활동 추적 개발
- [ ] 신고 기능 API 협의
- [ ] 신고 기능 개발
- [ ] 관리자 페이지 API 협의

**Comment by perman0519** [comment]
- [ ] OB service 추가 머지하기
- [ ] 2차스텝 팀 페이지 프론트와 설계하기

**Comment by KRimwoo** [comment]
- [ ] privacy, signup, find-account 페이지 디자인에 맞춰 리팩토링
- [ ]

**Comment by wochae** [comment]
- [ ] socket 관련 엔티티 설계하기

**Comment by HiHoi** [comment]
- [ ] 프론트엔드 현재 작업 상황 정리
- [ ] PWA 배너 정리
- [ ] 팀 페이지 토큰 문제 해결
- [ ] 인수인계 프로젝트 생성
- [ ] 팀 리스트 페이지 디자인
