### ISSUE TITLE
2023-11-10-TODO

### ISSUE THREAD

**Issue by joonseong11** [peer-42seoul/mangement-team-todo#2]
# 투두리스트 작성하는 법
### 참고사항
본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)

**Comment by SaltySalt77** [comment]
#### 운영진 업무
    - [ ] 운영사무국 디엠 답장

#### 개발진
- [ ] 로그인 qa 진행
- [ ] pr 밀린 것 진행

**Comment by juhyeonlee134** [comment]
- [ ] PR 리뷰
- [ ] 모집 글 수정 QA
- [ ] 모집 글 지원 QA
- [ ] Git wiki 최신화 (https://github.com/peer-42seoul/Peer-Backend/wiki/06-%E2%80%90-02-%E2%80%90-My-Page-(Profile)-Wiki)

**Comment by wochae** [comment]
- [ ] QA 진행
- [ ] chatGPT api 문서보기

**Comment by hyeon81** [comment]
- [ ] 세부옵션 api 연결 확인
- [ ] 폼페이지 제출 시 404 뜨는 에러 수정
- [ ] 무한 스크롤이 무한으로 되는 문제 수정

**Comment by Paul2021-R** [comment]
- [ ]  PR 리뷰
- [ ] 깃액션 뜯어고치기 
- [ ] 세부기획 점검 및 2차 스텝 진행 계획 세우기
- [ ] 쪽지 개선

**Comment by yoouyeon** [comment]
> 오늘은 다른 일정이 있어 코어타임 참석은 불가능합니다..

- [ ] PR 리뷰
- [ ] 어제 완성하지 못한 전체선택 / 해제 기능 마무리하기
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/252 해결

**Comment by heehoh** [comment]
- [ ] 회원탈퇴 QA
- [ ] 커스텀 컴포넌트로 개인정보 페이지 리펙토링

**Comment by KRimwoo** [comment]
- [ ] 회원가입, 소셜회원가입 QA
- [ ] 소셜계정 연동하기 버튼 논의 & 추가

**Comment by sinryuji** [comment]
- [ ] 사용자 추적 모듈 구현
- [ ] 유저탈퇴
- [ ] 팀 파트

**Comment by joonseong11** [comment]
- [ ] 인터뷰 답변 로직 변경 (api 와 데이터 타입 통일 및 로직 변경)
- [ ] 대표이미지 관련 부분에서 연동 의심 문제가 발견되서 해결예정
- [ ] QA 진행예정

**Comment by HiHoi** [comment]
- [ ] 새롭게 생긴 프로세스 동기화
- [ ] 팀 설정 페이지 내 타입 정리
- [ ] 검색 페이지 내 타입 정리
- [ ] 팀 설정 페이지의 팀 역활 정리 기능 추가

**Comment by weejihye** [comment]
- [ ] 세부기획 참여
- [ ] 핫픽스

**Comment by perman0519** [comment]
- [ ] 프론트와 qa진행
- [ ] dnd 설계
