### ISSUE TITLE
2023-12-04-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/mangement-team-todo#28]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by weejihye** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|12:30|외주기능정의서 마무리||
|12:30|13:30|외주 미팅||
|13:30|14:00|스크럼||
|14:00|~|쇼케이스 뷰페이지, 팀게시판(공지) 뷰, 작성페이지 작업||

**Comment by joonseong11** [comment]
### 1:00 ~ 10:00 작업가능 (선릉 위워크 2호점)
## 담당 및 현황
- 개인정보약관 페이지 (모바일 반응형 디자인 삽입필요)
- 모집글 작성, 수정 페이지 (QA 진행중, 디자인 작업중)
- 어드민 페이지 (와이어프레임, api 설계 완료)
## QA
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/382
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/374
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/317
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/322
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/348

|**시작 시간** | **종료 시간** | **제목** | **내용** | **완료 여부** |
|:---:|:---:|:---|:---|:---| 
|9:00|11:30|정형외과||✅| 
|11:30|12:30|리더스 회의||✅|
|||pr 확인|||
|||개인정보약관|모바일 반응형 디자인 반영||
|||J-TB 모집글 작성, 수정 QA||WIP|
