### ISSUE TITLE
2023-11-13 TODO

### ISSUE THREAD

**Issue by joonseong11** [peer-42seoul/mangement-team-todo#7]
지난 투두리스트 : https://github.com/peer-42seoul/mangement-team-todo/issues/2

# 투두리스트 작성하는 법
### 참고사항
본인의 작업 코드에 해당하는 이슈 링크 첨부 권장

# 분류된 작업
#### jujeon 
- 개인정보동의약관
- 모집글쓰기 작성 및 수정
- 히치하이킹
- 관리자페이지

#### hoslim
- 팀설정페이지
- 검색
- PWA

#### hyna
- 마이페이지, 프로필, 홈페이지설정
- 피어로그

#### hujeong
- 회원가입
- 탈퇴
- 마이페이지 개인정보

#### hyeokim2
- 메인페이지, 네비게이션바, 탭바
- 모집글 뷰
- DnD

#### jeyoon
- 팀페이지 메인화면
- 쪽지
- 툭박스(위젯)

#### woorikim
- 로그인
- 비밀번호 찾기
- 쇼케이스

#### haryu
- 알림 (nest)
- 쪽지
- socket (온라인 여부 관리 등)
- Algorithm (개인성향 측정, 팀평가)
#### jwee
- 게시판
- Algorithm (개인성향 측정, 팀평가)
- 피어로그
#### hyeongki
- 사용자추적
- 고나리자
- 인공지능 입출력 (chatGPT)
#### juhyelee
- 프로필
- 회원
- 피어로그
- 업적
#### junssong
- 회원
- 팀 (팀페이지, 팀설정 등)
#### wochae
- 알람 (스프링)
- 인공지능 입출력 (chatGPT)

**Comment by joonseong11** [comment]
- [ ] 2step 작업에서 관리자페이지 외에 와이어프레임이 필요한 작업부문 찾기 (종합 후 디자이너에게 전달예정)
- [ ] 2step 히치하이킹 추가필요 api 고민
- [ ] 인터뷰 답변 문제 발견 로직 변경 (api 와 데이터 타입 통일 및 로직 변경)
- [ ] 대표이미지 관련 부분에서 연동 의심 문제가 발견되서 해결예정

**Comment by KRimwoo** [comment]
- [ ] [비밀번호 찾기 페이지 fix](https://github.com/peer-42seoul/Peer-Frontend/issues/268)
- [ ] [recruit view 페이지 fix](https://github.com/peer-42seoul/Peer-Frontend/issues/269)

**Comment by juhyeonlee134** [comment]
- [ ] 관심목록 무한 조회 문제 (https://github.com/peer-42seoul/Peer-Backend/issues/329)
- [ ] ostep 메모리 가상화 공부
- [ ] philosopher 파악

**Comment by yoouyeon** [comment]
- [ ] 툴박스 - 위젯 기능 파악하기 (필요기술들 확인하기)
- [ ] 지원페이지 👉 쪽지 기능 개선 방법 고민
- [ ] 자바스크립트 스터디 준비 (책읽기...)

**Comment by wochae** [comment]
- [ ] chatGPT API docs 읽기
- [ ] 마이페이지 QA 진행

**Comment by SaltySalt77** [comment]
#### 회의 
- [ ] 11시 리더스 회의
- [ ] 11시 반 디자이너 회의

#### 개발
- [ ] mui theme provider로 모바일, pc typography varient 설정
- [ ] qa 빠진 부분 파악 및 진행

**Comment by hyeon81** [comment]
- [ ] pr 수정 https://github.com/peer-42seoul/Peer-Frontend/pull/282

- [ ] 각종 버그 수정 https://github.com/peer-42seoul/Peer-Frontend/issues/256https://github.com/peer-42seoul/Peer-Frontend/issues/257https://github.com/peer-42seoul/Peer-Frontend/issues/275

- [ ] 외주 작업 처리

**Comment by Paul2021-R** [comment]
### 회의

- [ ] 11시 리더스 회의 
- [ ] 11시 30분 디자이너 회의(미참석)  
- [ ] 4시 세부 기획 회의 

### 세부기획

- [ ] 알고리즘을 위한 개인평가 구조 세부 기획 
- [ ]  상단을 위한 세부 기획

### 개발 

- [ ] 쪽지, 사용자 패턴 정리 - 추가 로직 구상 및 재윤님과 공유
- [ ] 추가 작업해야하는 기능들 기능 세부 정리 및 구상

**Comment by sinryuji** [comment]
- [ ] team finish 추적
- [ ] team excel download

**Comment by heehoh** [comment]
- [ ] PR 리뷰
- [ ] 웹서브 공부

**Comment by perman0519** [comment]
- [ ] 2차 스텝 맡은 파트 공부 (몽고 db, DnD)

**Comment by weejihye** [comment]
-[ ] 모집글 다중 검색 쿼리 수정
