### ISSUE TITLE
2023-11-13-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/mangement-team-todo#8]
지난 이슈 : [지난 이슈 보기](https://github.com/peer-42seoul/mangement-team-todo/issues/2)
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)

**Comment by HiHoi** [comment]
- [ ] PWA 기본 설정
- [ ] 서비스 워커 틀 잡기
- [ ] 세부 기획
- [ ] 팀 설정 페이지 - 팀 직업(FE / BE / 디자이너 / 기획자 등) 추가
- [ ] 팀 설정 페이지 - 스터디 총원 설정 추가

**Comment by joonseong11** [comment]
- [ ] 리더회의
- [ ] 디자이너 미팅
- [ ] 2step 작업에서 관리자페이지 외에 와이어프레임이 필요한 작업부문 찾기 (종합 후 디자이너에게 전달예정)
- [ ] 2step 히치하이킹 추가필요 api 고민
- [ ] 인터뷰 답변 문제 발견 로직 변경 (api 와 데이터 타입 통일 및 로직 변경)
- [ ] 대표이미지 관련 부분에서 연동 의심 문제가 발견되서 해결예정
