### ISSUE TITLE
2023-11-14-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/mangement-team-todo#9]
지난 투두리스트 : https://github.com/peer-42seoul/mangement-team-todo/issues/7

# 투두리스트 작성하는 법
### 참고사항
본인의 작업 코드에 해당하는 이슈 링크 첨부 권장

# 분류된 작업
#### jujeon 
- 개인정보동의약관
- 모집글쓰기 작성 및 수정
- 히치하이킹
- 관리자페이지

#### hoslim
- 팀설정페이지
- 검색
- PWA

#### hyna
- 마이페이지, 프로필, 홈페이지설정
- 피어로그

#### hujeong
- 회원가입
- 탈퇴
- 마이페이지 개인정보

#### hyeokim2
- 메인페이지, 네비게이션바, 탭바
- 모집글 뷰
- DnD

#### jeyoon
- 팀페이지 메인화면
- 쪽지
- 툭박스(위젯)

#### woorikim
- 로그인
- 비밀번호 찾기
- 쇼케이스

#### haryu
- 알림 (nest)
- 쪽지
- socket (온라인 여부 관리 등)
- Algorithm (개인성향 측정, 팀평가)
#### jwee
- 게시판
- Algorithm (개인성향 측정, 팀평가)
- 피어로그
#### hyeongki
- 사용자추적
- 고나리자
- 인공지능 입출력 (chatGPT)
#### juhyelee
- 프로필
- 회원
- 피어로그
- 업적
#### junssong
- 회원
- 팀 (팀페이지, 팀설정 등)
#### wochae
- 알람 (스프링)
- 인공지능 입출력 (chatGPT)

**Comment by Paul2021-R** [comment]
- [ ] 쪽지 사용자 시나리오 작성하기 
- [ ] 피어레벨 기획 진행하기
- [ ] 쪽지 QA 상태 파악하기  
- [ ] 쪽지 작업 진행하기

**Comment by SaltySalt77** [comment]
#### 운영진
- [ ] 회의 참석
- [ ] 베스트 피어로그 후보 선정

#### 개발진
- [ ] 피어로그 기획 파악 및 정리
- [ ] api 관련논의 및 정리
- [ ] pr review 진행

**Comment by juhyeonlee134** [comment]
- [ ] PR 리뷰 받기
- [ ] 2step 확인 및 파악
- [ ] 프로필 수정 해결

**Comment by yoouyeon** [comment]
- [ ] PR 확인
- [ ] 쪽지 개선사항 고민 / (가능하면) 작업까지
  - 전체선택해제 기능 관련 구조 확정짓기
  - api 개선사항 (무한스크롤, useSWR)
  - 삭제된 메시지 / 모집글에서 쪽지
- [ ] QA 진행
- [ ] Step 2 세부기획 읽어보기
- [ ] 캘린더 라이브러리 만져보기 (React Fullcalendar, MUI Calendar)

**Comment by hyeon81** [comment]
- [ ] pr 확인
- [ ] 메인페이지, 모집글뷰페이지 qa
- [ ] 2차스텝 명세 파악

**Comment by wochae** [comment]
- [ ] PR 확인
- [ ] QA 진행
- [ ] chatGPT docs 따라해보기
---

- [ ] 학교 과제 제출

**Comment by joonseong11** [comment]
- [ ] 인터뷰 답변 문제 발견 로직 변경 (api 와 데이터 타입 통일 및 로직 변경)
- [ ] 대표이미지 관련 부분에서 연동 의심 문제가 발견되서 해결예정
- [ ] 모집글쓰기 세부 디자인 입히기

**Comment by sinryuji** [comment]
- [ ] team finish 추적
- [ ] 유저 활동 추적

**Comment by perman0519** [comment]
- [ ] 리뷰 맡은 pr 대면 리뷰받기
- [ ] 2차 세부기획 읽고 습득

**Comment by HiHoi** [comment]
- [ ] 팀 설정 페이지 - 스터디 총 인원 수정 API 작성
- [ ] 팀 설정 페이지 - 프로젝트 역할별 인원 설정
- [ ] PWA - 프리캐싱 작성

**Comment by weejihye** [comment]
- [ ] exam05.....fail......
- [ ] 주전님과 상담
- [ ] 메인 페이지 pagenation 수정, 메인 페이지 검색 status, place 검색 조건 수정, due 검색 조건 수정
- [ ] 히치하이킹 api 논의
- [ ] 개별 성향 평가 항목 작성중
